/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VinsonRouteImport } from './routes/vinson'
import { Route as UsuariosRouteImport } from './routes/usuarios'
import { Route as ProyeccionesRouteImport } from './routes/proyecciones'
import { Route as PercentagesRouteImport } from './routes/percentages'
import { Route as GedisRouteImport } from './routes/gedis'
import { Route as DocumentosRouteImport } from './routes/documentos'
import { Route as CargaManualRouteImport } from './routes/carga-manual'
import { Route as AgenteRouteImport } from './routes/agente'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiPublicHooksVinsonDailyRouteImport } from './routes/api/public/hooks/vinson-daily'

const VinsonRoute = VinsonRouteImport.update({
  id: '/vinson',
  path: '/vinson',
  getParentRoute: () => rootRouteImport,
} as any)
const UsuariosRoute = UsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const ProyeccionesRoute = ProyeccionesRouteImport.update({
  id: '/proyecciones',
  path: '/proyecciones',
  getParentRoute: () => rootRouteImport,
} as any)
const PercentagesRoute = PercentagesRouteImport.update({
  id: '/percentages',
  path: '/percentages',
  getParentRoute: () => rootRouteImport,
} as any)
const GedisRoute = GedisRouteImport.update({
  id: '/gedis',
  path: '/gedis',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentosRoute = DocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => rootRouteImport,
} as any)
const CargaManualRoute = CargaManualRouteImport.update({
  id: '/carga-manual',
  path: '/carga-manual',
  getParentRoute: () => rootRouteImport,
} as any)
const AgenteRoute = AgenteRouteImport.update({
  id: '/agente',
  path: '/agente',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksVinsonDailyRoute =
  ApiPublicHooksVinsonDailyRouteImport.update({
    id: '/api/public/hooks/vinson-daily',
    path: '/api/public/hooks/vinson-daily',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agente': typeof AgenteRoute
  '/carga-manual': typeof CargaManualRoute
  '/documentos': typeof DocumentosRoute
  '/gedis': typeof GedisRoute
  '/percentages': typeof PercentagesRoute
  '/proyecciones': typeof ProyeccionesRoute
  '/usuarios': typeof UsuariosRoute
  '/vinson': typeof VinsonRoute
  '/api/chat': typeof ApiChatRoute
  '/api/public/hooks/vinson-daily': typeof ApiPublicHooksVinsonDailyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agente': typeof AgenteRoute
  '/carga-manual': typeof CargaManualRoute
  '/documentos': typeof DocumentosRoute
  '/gedis': typeof GedisRoute
  '/percentages': typeof PercentagesRoute
  '/proyecciones': typeof ProyeccionesRoute
  '/usuarios': typeof UsuariosRoute
  '/vinson': typeof VinsonRoute
  '/api/chat': typeof ApiChatRoute
  '/api/public/hooks/vinson-daily': typeof ApiPublicHooksVinsonDailyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agente': typeof AgenteRoute
  '/carga-manual': typeof CargaManualRoute
  '/documentos': typeof DocumentosRoute
  '/gedis': typeof GedisRoute
  '/percentages': typeof PercentagesRoute
  '/proyecciones': typeof ProyeccionesRoute
  '/usuarios': typeof UsuariosRoute
  '/vinson': typeof VinsonRoute
  '/api/chat': typeof ApiChatRoute
  '/api/public/hooks/vinson-daily': typeof ApiPublicHooksVinsonDailyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agente'
    | '/carga-manual'
    | '/documentos'
    | '/gedis'
    | '/percentages'
    | '/proyecciones'
    | '/usuarios'
    | '/vinson'
    | '/api/chat'
    | '/api/public/hooks/vinson-daily'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agente'
    | '/carga-manual'
    | '/documentos'
    | '/gedis'
    | '/percentages'
    | '/proyecciones'
    | '/usuarios'
    | '/vinson'
    | '/api/chat'
    | '/api/public/hooks/vinson-daily'
  id:
    | '__root__'
    | '/'
    | '/agente'
    | '/carga-manual'
    | '/documentos'
    | '/gedis'
    | '/percentages'
    | '/proyecciones'
    | '/usuarios'
    | '/vinson'
    | '/api/chat'
    | '/api/public/hooks/vinson-daily'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgenteRoute: typeof AgenteRoute
  CargaManualRoute: typeof CargaManualRoute
  DocumentosRoute: typeof DocumentosRoute
  GedisRoute: typeof GedisRoute
  PercentagesRoute: typeof PercentagesRoute
  ProyeccionesRoute: typeof ProyeccionesRoute
  UsuariosRoute: typeof UsuariosRoute
  VinsonRoute: typeof VinsonRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiPublicHooksVinsonDailyRoute: typeof ApiPublicHooksVinsonDailyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vinson': {
      id: '/vinson'
      path: '/vinson'
      fullPath: '/vinson'
      preLoaderRoute: typeof VinsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usuarios': {
      id: '/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof UsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proyecciones': {
      id: '/proyecciones'
      path: '/proyecciones'
      fullPath: '/proyecciones'
      preLoaderRoute: typeof ProyeccionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/percentages': {
      id: '/percentages'
      path: '/percentages'
      fullPath: '/percentages'
      preLoaderRoute: typeof PercentagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gedis': {
      id: '/gedis'
      path: '/gedis'
      fullPath: '/gedis'
      preLoaderRoute: typeof GedisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentos': {
      id: '/documentos'
      path: '/documentos'
      fullPath: '/documentos'
      preLoaderRoute: typeof DocumentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carga-manual': {
      id: '/carga-manual'
      path: '/carga-manual'
      fullPath: '/carga-manual'
      preLoaderRoute: typeof CargaManualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agente': {
      id: '/agente'
      path: '/agente'
      fullPath: '/agente'
      preLoaderRoute: typeof AgenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/vinson-daily': {
      id: '/api/public/hooks/vinson-daily'
      path: '/api/public/hooks/vinson-daily'
      fullPath: '/api/public/hooks/vinson-daily'
      preLoaderRoute: typeof ApiPublicHooksVinsonDailyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgenteRoute: AgenteRoute,
  CargaManualRoute: CargaManualRoute,
  DocumentosRoute: DocumentosRoute,
  GedisRoute: GedisRoute,
  PercentagesRoute: PercentagesRoute,
  ProyeccionesRoute: ProyeccionesRoute,
  UsuariosRoute: UsuariosRoute,
  VinsonRoute: VinsonRoute,
  ApiChatRoute: ApiChatRoute,
  ApiPublicHooksVinsonDailyRoute: ApiPublicHooksVinsonDailyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
