/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VinsonRouteImport } from './routes/vinson'
import { Route as PercentagesRouteImport } from './routes/percentages'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicHooksVinsonDailyRouteImport } from './routes/api/public/hooks/vinson-daily'

const VinsonRoute = VinsonRouteImport.update({
  id: '/vinson',
  path: '/vinson',
  getParentRoute: () => rootRouteImport,
} as any)
const PercentagesRoute = PercentagesRouteImport.update({
  id: '/percentages',
  path: '/percentages',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksVinsonDailyRoute =
  ApiPublicHooksVinsonDailyRouteImport.update({
    id: '/api/public/hooks/vinson-daily',
    path: '/api/public/hooks/vinson-daily',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/percentages': typeof PercentagesRoute
  '/vinson': typeof VinsonRoute
  '/api/public/hooks/vinson-daily': typeof ApiPublicHooksVinsonDailyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/percentages': typeof PercentagesRoute
  '/vinson': typeof VinsonRoute
  '/api/public/hooks/vinson-daily': typeof ApiPublicHooksVinsonDailyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/percentages': typeof PercentagesRoute
  '/vinson': typeof VinsonRoute
  '/api/public/hooks/vinson-daily': typeof ApiPublicHooksVinsonDailyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/percentages' | '/vinson' | '/api/public/hooks/vinson-daily'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/percentages' | '/vinson' | '/api/public/hooks/vinson-daily'
  id:
    | '__root__'
    | '/'
    | '/percentages'
    | '/vinson'
    | '/api/public/hooks/vinson-daily'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PercentagesRoute: typeof PercentagesRoute
  VinsonRoute: typeof VinsonRoute
  ApiPublicHooksVinsonDailyRoute: typeof ApiPublicHooksVinsonDailyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vinson': {
      id: '/vinson'
      path: '/vinson'
      fullPath: '/vinson'
      preLoaderRoute: typeof VinsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/percentages': {
      id: '/percentages'
      path: '/percentages'
      fullPath: '/percentages'
      preLoaderRoute: typeof PercentagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/vinson-daily': {
      id: '/api/public/hooks/vinson-daily'
      path: '/api/public/hooks/vinson-daily'
      fullPath: '/api/public/hooks/vinson-daily'
      preLoaderRoute: typeof ApiPublicHooksVinsonDailyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PercentagesRoute: PercentagesRoute,
  VinsonRoute: VinsonRoute,
  ApiPublicHooksVinsonDailyRoute: ApiPublicHooksVinsonDailyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
